# See the dedicated "version" documentation section.
version: '2'

run:
  timeout: 5m

linters:
  default: all
  disable:
    # depguard checks if package imports are in a list of acceptable packages.
    # Disabled as we rely on go.mod and strict import lists are not defined yet.
    - depguard
    # musttag enforces that exported struct fields have specific tags (e.g. json, xml).
    # Disabled because many internal domain structs do not require serialization tags.
    - musttag
    # funlen detects long functions.
    # Disabled to avoid artificial splitting of code; we use cyclomatic complexity instead.
    - funlen
    # forbidigo forbids usage of specific identifiers.
    # Disabled as we currently have no banned identifiers.
    - forbidigo
    # godox detects TODO and FIXME comments.
    # Disabled because TODOs are acceptable tracking mechanisms during development.
    - godox
    # tagalign checks that struct tags are well aligned.
    # Disabled as it adds noise to diffs and conflicts with standard formatting.
    - tagalign
    # ireturn enforces returning concrete types instead of interfaces.
    # Disabled because our hexagonal architecture relies on interface returns for ports.
    - ireturn
    # nlreturn checks for a new line before return and branch statements.
    # Disabled as it enforces excessive vertical spacing.
    - nlreturn
    # noinlineerr checks for inline error handling (if err := ...; err != nil).
    # Disabled because inline error checks are idiomatic and concise in Go.
    - noinlineerr
    # wsl (Whitespace Linter) enforces specific empty line usage.
    # Disabled as strict whitespace rules can be too opinionated for this project.
    - wsl
    # the following linters should be enabled once packages have been refactored
    # exhaustruct checks if all struct fields are initialized.
    - exhaustruct
    # lll checks for line length limits.
    - lll

  settings:
    varnamelen:
      min-name-length: 2
      ignore-names:
        - i
        - j
        - k
        - v
    tagliatelle:
      case:
        use-field-name: true
        rules:
          json: camel
          env: goCamel
    godot:
      period: false
    wrapcheck:
      ignore-sigs:
        - json.Marshal(
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
    cyclop:
      max-complexity: 12
    govet:
      enable-all: true
      disable:
        - fieldalignment
  exclusions:
    rules:
      - path: 'infra/'
        linters:
          - gosec
      - path: 'sample_files/'
        linters:
          - gosec

formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
    #- gci
    #- swaggo
  settings:
    gofmt:
      # Simplify code: gofmt with `-s` option.
      # Default: true
      simplify: false
      # Apply the rewrite rules to the source before reformatting.
      # https://pkg.go.dev/cmd/gofmt
      # Default: []
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
    gofumpt:
      # Module path which contains the source code being formatted.
      # Default: ""
      module-path: github.com/fclimited/c1-openspec-demo
      # Choose whether to use the extra rules.
      # Default: false
      extra-rules: true
    goimports:
      # A list of prefixes, which, if set, checks import paths
      # with the given prefixes are grouped after 3rd-party packages.
      # Default: []
      local-prefixes:
        - github.com/fclimited/c1-openspec-demo
    golines:
      # Target maximum line length.
      # Default: 100
      max-len: 120
      # Length of a tabulation.
      # Default: 4
      tab-len: 2
      # Shorten single-line comments.
      # Default: false
      shorten-comments: true
      # Default: true
      reformat-tags: false
      # Split chained methods on the dots as opposed to the arguments.
      # Default: true
      chain-split-dots: true
