name: 'Build Wails App'
description: 'Sets up environment and builds the Wails application'
inputs:
  go-version:
    description: 'Go version to use'
    required: true
    default: '1.25'
  node-version:
    description: 'Node version to use'
    required: true
    default: '24'
  build-flags:
    description: 'Additional flags for wails build'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: true

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev

    - name: Install Wails
      shell: bash
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Build
      shell: bash
      run: |
        FLAGS="${{ inputs.build-flags }}"
        if [ "$RUNNER_OS" == "Linux" ]; then
          FLAGS="$FLAGS -tags webkit2_41"
        fi
        wails build $FLAGS